import type { ExamQuestion } from "./types";

const fiftyDaysExam: ExamQuestion[] = [
  {
    id: "exam-50d-1",
    prompt: "다음 중 소수는 몇 개인가요? { 9, 11, 21, 23, 27 }",
    choices: ["1개", "2개", "3개", "4개"],
    answerIndex: 1,
    hint: "9=3×3, 21=3×7, 27=3³은 합성수예요. 11과 23만 소수예요.",
  },
  {
    id: "exam-50d-2",
    prompt: "1은 소수인가요, 합성수인가요, 단위수인가요?",
    choices: ["소수", "합성수", "단위수", "짝수"],
    answerIndex: 2,
    hint: "1은 약수가 자기 자신 하나뿐이라 소수의 정의에도, 합성수의 정의에도 맞지 않아요.",
  },
  {
    id: "exam-50d-3",
    prompt: "60을 소인수분해하면?",
    choices: ["2² × 3 × 5", "2 × 3² × 5", "2³ × 3 × 5", "2² × 3 × 5²"],
    answerIndex: 0,
    hint: "60 = 6 × 10 = (2×3) × (2×5)예요.",
  },
  {
    id: "exam-50d-4",
    prompt: "3 × 5 × 11의 인수가 아닌 것은?",
    choices: ["15", "22", "33", "55"],
    answerIndex: 1,
    hint: "22 = 2×11인데 이 곱셈식에는 2가 없어요. 15=3×5, 33=3×11, 55=5×11은 모두 인수예요.",
  },
  {
    id: "exam-50d-5",
    prompt: "16과 24의 최대공약수는?",
    choices: ["4", "6", "8", "12"],
    answerIndex: 2,
    hint: "16=2⁴, 24=2³×3. 공통 소인수는 2뿐이고, 더 작은 지수는 2³=8이에요.",
  },
  {
    id: "exam-50d-6",
    prompt: "16과 24의 최소공배수는?",
    choices: ["24", "48", "96", "144"],
    answerIndex: 1,
    hint: "16=2⁴, 24=2³×3. 지수가 더 큰 2⁴와, 한쪽에만 있는 3을 모두 곱하면 2⁴×3=48이에요.",
  },
  {
    id: "exam-50d-7",
    prompt: "두 수 A=2×3²×5, B=2²×3×7의 최대공약수는?",
    choices: ["2×3", "2²×3²", "2×3×5", "6"],
    answerIndex: 0,
    hint: "공통 소인수는 2와 3뿐이고, 각각 더 작은 지수(1)를 선택하면 2¹×3¹=6이에요.",
  },
  {
    id: "exam-50d-8",
    prompt: "두 수가 서로소일 때, 이 둘의 최대공약수는 항상 얼마인가요?",
    choices: ["0", "1", "두 수의 곱", "알 수 없다"],
    answerIndex: 1,
    hint: "서로소의 정의 자체가 '공약수가 1뿐인 관계'예요.",
  },
  {
    id: "exam-50d-9",
    prompt: "0.6 × 0.7을 계산하면?",
    choices: ["0.42", "4.2", "0.042", "42"],
    answerIndex: 0,
    hint: "소수점 무시하고 6×7=42, 소수점 뒤 자릿수 1+1=2개만큼 다시 소수점을 찍어요.",
  },
  {
    id: "exam-50d-10",
    prompt: "-6의 역수는?",
    choices: ["6", "-6", "1/6", "-1/6"],
    answerIndex: 3,
    hint: "부호는 그대로 두고 분자·분모만 뒤집어요. -6 = -6/1 → -1/6.",
  },
  {
    id: "exam-50d-11",
    prompt: "3x² − 2x + 7에서 항은 몇 개이고, 상수항은 무엇인가요?",
    choices: ["항 2개, 상수항 −2", "항 3개, 상수항 7", "항 3개, 상수항 −2x", "항 2개, 상수항 7"],
    answerIndex: 1,
    hint: "+로 연결된 각각이 항이에요: 3x², −2x, 7 세 개. 숫자로만 된 항이 상수항이에요.",
  },
  {
    id: "exam-50d-12",
    prompt: "x³ − 2x² + 4의 최고차항의 차수는?",
    choices: ["1차", "2차", "3차", "4차"],
    answerIndex: 2,
    hint: "차수가 가장 높은 항을 찾아보세요. x³이 가장 높은 3차항이에요.",
  },
  {
    id: "exam-50d-13",
    prompt: "a⁵ ÷ a² × a를 계산하면?",
    choices: ["a²", "a⁴", "a⁶", "a⁸"],
    answerIndex: 1,
    hint: "나눌 때는 빼고(5−2=3), 곱할 때는 더해요(3+1=4).",
  },
  {
    id: "exam-50d-14",
    prompt: "x² − 12x + 36을 인수분해하면?",
    choices: ["(x − 6)²", "(x + 6)²", "(x − 12)(x − 3)", "(x − 6)(x + 6)"],
    answerIndex: 0,
    hint: "36=6². 가운데 항 −12x가 2×x×(−6)과 일치하는지 확인해보세요.",
  },
  {
    id: "exam-50d-15",
    prompt: "a + b = 5, ab = 2일 때 a² + b²의 값은?",
    choices: ["21", "25", "29", "10"],
    answerIndex: 0,
    hint: "a²+b² = (a+b)² − 2ab = 25 − 4 = 21.",
  },
  {
    id: "exam-50d-16",
    prompt: "ax + 5 = 3x + b가 x에 관한 항등식일 때, a + b의 값은?",
    choices: ["6", "7", "8", "9"],
    answerIndex: 2,
    hint: "계수비교법으로 a=3, b=5예요. a+b=8.",
  },
  {
    id: "exam-50d-17",
    prompt: "x³ − 2를 x − 1로 나눈 나머지는?",
    choices: ["−2", "−1", "0", "1"],
    answerIndex: 1,
    hint: "나머지정리: 1차식 x−1을 0으로 만드는 x=1을 대입해요. 1−2=−1.",
  },
  {
    id: "exam-50d-18",
    prompt: "0.4를 분수로 나타내면?",
    choices: ["4/10", "1/4", "4/100", "40/1"],
    answerIndex: 0,
    hint: "소수점 뒤 숫자 1개 → 분모에 0을 1개, 분자는 소수점 무시하고 그대로.",
  },
  {
    id: "exam-50d-19",
    prompt: "√48을 간단히 하면?",
    choices: ["4√3", "3√4", "16√3", "2√12"],
    answerIndex: 0,
    hint: "48 = 16 × 3, 16은 제곱수라서 4가 밖으로 나와요.",
  },
  {
    id: "exam-50d-20",
    prompt: "i³의 값은?",
    choices: ["i", "−1", "−i", "1"],
    answerIndex: 2,
    hint: "i² = −1이므로 i³ = i²×i = −i.",
  },
  {
    id: "exam-50d-21",
    prompt: "a < 0일 때 |a| + a의 값은?",
    choices: ["0", "2a", "−2a", "a"],
    answerIndex: 0,
    hint: "a가 음수면 |a| = −a. −a + a = 0.",
  },
  {
    id: "exam-50d-22",
    prompt: "3(x − 2) = x + 4를 풀면 x는?",
    choices: ["3", "4", "5", "6"],
    answerIndex: 2,
    hint: "전개하면 3x−6=x+4, 이항하면 2x=10, x=5.",
  },
  {
    id: "exam-50d-23",
    prompt: "x²+2x−15=0의 두 근을 곱하면?",
    choices: ["−15", "15", "2", "−2"],
    answerIndex: 0,
    hint: "(x+5)(x−3)=0 → 근은 −5, 3. 곱하면 상수항 −15.",
  },
  {
    id: "exam-50d-24",
    prompt: "삼각형의 한 외각은 무엇과 크기가 같나요?",
    choices: ["이웃한 내각", "나머지 두 내각의 합", "180도", "가장 큰 내각"],
    answerIndex: 1,
    hint: "외각 정리: 외각 = 이웃하지 않는 두 내각의 합.",
  },
  {
    id: "exam-50d-25",
    prompt: "반지름이 r인 원의 넓이는?",
    choices: ["2πr", "πr", "πr²", "2πr²"],
    answerIndex: 2,
    hint: "원의 넓이 공식은 πr².",
  },
  {
    id: "exam-50d-26",
    prompt: "세 변의 수직이등분선이 만나는 점(외심)까지 세 꼭짓점의 거리는 어떤 관계인가요?",
    choices: ["항상 다르다", "모두 같다(외접원의 반지름)", "두 개만 같다", "관계없다"],
    answerIndex: 1,
    hint: "외심은 세 꼭짓점까지의 거리가 모두 같은 점이에요.",
  },
  {
    id: "exam-50d-27",
    prompt: "평행사변형의 두 대각선의 성질은?",
    choices: ["항상 길이가 같다", "서로 이등분한다", "항상 수직이다", "평행하다"],
    answerIndex: 1,
    hint: "평행사변형의 대각선은 서로를 정확히 반으로 나눠요.",
  },
  {
    id: "exam-50d-28",
    prompt: "삼각형의 무게중심은 각 중선을 어떤 비율로 나누나요?",
    choices: ["1대1", "2대1", "3대1", "1대2"],
    answerIndex: 1,
    hint: "무게중심은 중선을 꼭짓점 쪽이 2, 변 쪽이 1이 되도록 나눠요.",
  },
  {
    id: "exam-50d-29",
    prompt: "직각삼각형의 두 변이 9와 12일 때 빗변의 길이는?",
    choices: ["13", "15", "18", "21"],
    answerIndex: 1,
    hint: "9²+12²=81+144=225, √225=15.",
  },
  {
    id: "exam-50d-30",
    prompt: "tan θ를 sin θ와 cos θ로 나타내면?",
    choices: ["sin θ × cos θ", "sin θ / cos θ", "cos θ / sin θ", "sin θ + cos θ"],
    answerIndex: 1,
    hint: "탄젠트는 코사인분의 사인.",
  },
  {
    id: "exam-50d-31",
    prompt: "지름에 대한 원주각의 크기는?",
    choices: ["45도", "60도", "90도", "180도"],
    answerIndex: 2,
    hint: "지름의 중심각 180도의 절반이 원주각이에요.",
  },
  {
    id: "exam-50d-32",
    prompt: "두 점 A(0,0), B(6,8) 사이의 거리는?",
    choices: ["8", "10", "12", "14"],
    answerIndex: 1,
    hint: "√(6²+8²)=√100=10.",
  },
  {
    id: "exam-50d-33",
    prompt: "기울기가 3인 직선에 수직인 직선의 기울기는?",
    choices: ["3", "-3", "1/3", "-1/3"],
    answerIndex: 3,
    hint: "역수를 취하고 부호를 바꿔요: 3 → 1/3 → -1/3.",
  },
  {
    id: "exam-50d-34",
    prompt: "중심 (1,2), 반지름 5인 원의 방정식은?",
    choices: ["(x-1)²+(y-2)²=5", "(x-1)²+(y-2)²=25", "(x+1)²+(y+2)²=25", "(x-1)²+(y-2)²=10"],
    answerIndex: 1,
    hint: "중심 좌표를 부호 바꿔 넣고, 반지름은 제곱해서 25.",
  },
  {
    id: "exam-50d-35",
    prompt: "y=f(x)의 그래프를 x축 방향 2, y축 방향 -3만큼 평행이동한 그래프의 식은?",
    choices: ["y=f(x-2)-3", "y=f(x+2)+3", "y+3=f(x-2)", "y-3=f(x+2)"],
    answerIndex: 2,
    hint: "부호를 바꿔서 대입: x 대신 x-2, y 대신 y-(-3)=y+3 → y-(-3)=f(x-2) 즉 y+3=f(x-2).",
  },
  {
    id: "exam-50d-36",
    prompt: "부등식 y < (경계선의 식)이 나타내는 영역은?",
    choices: ["경계선 위쪽", "경계선 아래쪽", "경계선 자체", "전체 평면"],
    answerIndex: 1,
    hint: "y 기준으로 작다는 것은 경계선보다 아래쪽에 있다는 뜻.",
  },
  {
    id: "exam-50d-37",
    prompt: "z = 4 - 3i 일 때 z × z̄ 의 값은?",
    choices: ["7", "25", "-9", "16"],
    answerIndex: 1,
    hint: "실수부 제곱 + 허수부 제곱: 4²+3²=25.",
  },
  {
    id: "exam-50d-38",
    prompt: "x³-27을 인수분해하면?",
    choices: ["(x-3)(x²+3x+9)", "(x-3)(x²-3x+9)", "(x-3)³", "(x+3)(x²-3x+9)"],
    answerIndex: 0,
    hint: "27=3³이니까 a³-b³=(a-b)(a²+ab+b²) 공식에서 (x-3)(x²+3x+9).",
  },
  {
    id: "exam-50d-39",
    prompt: "x²+12x+□가 완전제곱식이 되기 위한 □의 값은?",
    choices: ["12", "24", "36", "144"],
    answerIndex: 2,
    hint: "1차항 계수 12의 절반(6)을 제곱하면 36.",
  },
  {
    id: "exam-50d-40",
    prompt: "3/4의 역수는?",
    choices: ["4/3", "-3/4", "3/4", "-4/3"],
    answerIndex: 0,
    hint: "역수는 분자·분모를 뒤집은 수.",
  },
  {
    id: "exam-50d-41",
    prompt: "'4의 제곱근'을 구하면?",
    choices: ["2", "±2", "4", "16"],
    answerIndex: 1,
    hint: "숫자가 '제곱근' 앞에 있으면 x²=4의 해 — 답은 두 개.",
  },
];

export const examsByCourse: Record<string, ExamQuestion[]> = {
  "math-basic/50days": fiftyDaysExam,
};

export function getExam(subjectSlug: string, courseSlug: string): ExamQuestion[] | undefined {
  return examsByCourse[`${subjectSlug}/${courseSlug}`];
}
